DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
)

-- create
INSERT INTO TB_HEROIS (NOME, PODER)
VALUES 
  ('Fkash','Velocidade'),
  ('Aquaman','Agua'),
  ('Batman','Dinheiro')

--read 
SELECT * FROM TB_HEROIS
SELECT nome, poder FROM TB_HEROIS where ID = 2

--update
UPDATE TB_HEROIS
SET NOME = 'Flash'
WHERE ID = 1